name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Node.js 
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3) Install dependencies
      - name: Install dependencies
        run: npm install

      # 4) Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # 5) Build the React app
      - name: Build
        run: npm run build
